using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

namespace GenericAotPipelines.Generators.Tests;

public class DecoratorGeneratorTests
{
    [Fact]
    public async Task GenerationTest()
    {
        // Arrange
        string source = """
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;

using GenericAotPipelines;

namespace FooHandlers.Handlers
{
    public interface IFooHandler : IRequestHandler<bool, string>;

    [UsePipeline<Pipeline<bool, string>>]
    internal sealed partial class FooHandler : IFooHandler
    {
        public ValueTask<string> HandleAsync(bool request, CancellationToken ct = default)
        {
            return ValueTask.FromResult( request.ToString() );
        }
    }
}
""";

        string expectedGeneratedCode = """
// <auto-generated/>

#pragma warning disable
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace GenericAotPipelines.Generated.Decorators
{
    [global::System.CodeDom.Compiler.GeneratedCode("GenericAotPipelines.Generators.DecoratorGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class FooHandlers_Handlers_FooHandler_Decorator
        : DecoratedRequestHandler<bool, string>
        , FooHandlers.Handlers.IFooHandler
    {
        public FooHandlers_Handlers_FooHandler_Decorator(
            GenericAotPipelines.Pipeline<bool, string> pipeline,
            FooHandlers.Handlers.FooHandler handler)
            : base(pipeline, handler)
        {
        }
        
        public static void RegisterDecoratedHandler(IServiceCollection services)
        {
            services
                .AddTransient<FooHandlers.Handlers.FooHandler>()
                .AddTransient<FooHandlers.Handlers.IFooHandler, FooHandlers_Handlers_FooHandler_Decorator>();
        }
    }
}

""";

        string expectedGeneratedCode2 = """
// <auto-generated/>

#pragma warning disable
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace GenericAotPipelines.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCode("GenericAotPipelines.Generators.DecoratorGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class RegistrationExtensions
    {
        public static IServiceCollection RegisterDecoratedRequestHandlers(this IServiceCollection services)
        {
            Decorators.FooHandlers_Handlers_FooHandler_Decorator.RegisterDecoratedHandler(services);
            return services;
        }
    }
}

""";

        DecoratorGeneratorTest test = new()
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net90
                .AddPackages([
                    new PackageIdentity("Microsoft.Extensions.DependencyInjection.Abstractions", "9.0.8")
                ]),
            TestState =
            {
                Sources = { CodeBase.CommonCode, source },
                GeneratedSources =
                {
                    (typeof(DecoratorGenerator), "FooHandlerDecorator.g.cs", expectedGeneratedCode),
                    (typeof(DecoratorGenerator), "GenericAotPipelinesExtensions.g.cs", expectedGeneratedCode2)
                }
            }
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task EventTest()
    {
        // Arrange
        string source = """
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;

using GenericAotPipelines;

namespace FooHandlers.Handlers
{
    public interface IFooHandler : IRequestHandler<bool>;

    [UsePipeline<Pipeline<bool>>]
    internal sealed partial class FooHandler : IFooHandler
    {
        public ValueTask HandleAsync(bool request, CancellationToken ct = default)
        {
            return ValueTask.CompletedTask;
        }
    }
}
""";

        string expectedGeneratedCode = """
// <auto-generated/>

#pragma warning disable
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace GenericAotPipelines.Generated.Decorators
{
    [global::System.CodeDom.Compiler.GeneratedCode("GenericAotPipelines.Generators.DecoratorGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class FooHandlers_Handlers_FooHandler_Decorator
        : DecoratedRequestHandler<bool>
        , FooHandlers.Handlers.IFooHandler
    {
        public FooHandlers_Handlers_FooHandler_Decorator(
            GenericAotPipelines.Pipeline<bool> pipeline,
            FooHandlers.Handlers.FooHandler handler)
            : base(pipeline, handler)
        {
        }
        
        public static void RegisterDecoratedHandler(IServiceCollection services)
        {
            services
                .AddTransient<FooHandlers.Handlers.FooHandler>()
                .AddTransient<FooHandlers.Handlers.IFooHandler, FooHandlers_Handlers_FooHandler_Decorator>();
        }
    }
}

""";

        string expectedGeneratedCode2 = """
// <auto-generated/>

#pragma warning disable
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace GenericAotPipelines.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCode("GenericAotPipelines.Generators.DecoratorGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class RegistrationExtensions
    {
        public static IServiceCollection RegisterDecoratedRequestHandlers(this IServiceCollection services)
        {
            Decorators.FooHandlers_Handlers_FooHandler_Decorator.RegisterDecoratedHandler(services);
            return services;
        }
    }
}

""";

        DecoratorGeneratorTest test = new()
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net90
                .AddPackages([
                    new PackageIdentity("Microsoft.Extensions.DependencyInjection.Abstractions", "9.0.8")
                ]),
            TestState =
            {
                Sources = { CodeBase.CommonCode, source },
                GeneratedSources =
                {
                    (typeof(DecoratorGenerator), "FooHandlerDecorator.g.cs", expectedGeneratedCode),
                    (typeof(DecoratorGenerator), "GenericAotPipelinesExtensions.g.cs", expectedGeneratedCode2)
                }
            }
        };

        await test.RunAsync();
    }

    class DecoratorGeneratorTest : CSharpSourceGeneratorTest<DecoratorGenerator, DefaultVerifier>
    {
        //protected override CompilationOptions CreateCompilationOptions()
        //{
        //    var options = (CSharpCompilationOptions)base.CreateCompilationOptions();
        //    //options.With
        //
        //    return options.WithUsings(
        //        "System",
        //        "System.Threading",
        //        "System.Threading.Tasks");
        //}

        //protected override ParseOptions CreateParseOptions()
        //{
        //    var options = (CSharpParseOptions)base.CreateParseOptions();
        //    return options.WithLanguageVersion(LanguageVersion.Latest);
        //}
    }
}